// Copyright DWJ 2023.
// Distributed under the Boost Software License, Version 1.0.
// https://www.boost.org/LICENSE_1_0.txt

export const randResponsibilities = [
  "Answering customer inquiries",
  "Handling customer complaints",
  "Maintaining customer records",
  "Scheduling appointments",
  "Greeting customers",
  "Providing product information",
  "Processing payments",
  "Performing data entry",
  "Preparing reports",
  "Answering phone calls",
  "Handling mail and email",
  "Managing calendars",
  "Making travel arrangements",
  "Ordering office supplies",
  "Assisting with special projects",
  "Performing market research",
  "Coordinating events",
  "Organizing meetings",
  "Providing administrative support",
  "Preparing presentations",
  "Creating and maintaining databases",
  "Managing social media accounts",
  "Designing marketing materials",
  "Conducting interviews",
  "Training new employees",
  "Supervising other staff members",
  "Implementing company policies",
  "Ensuring compliance with regulations",
  "Reviewing and approving invoices",
  "Preparing budgets",
];
